const API='/api';let me=null;const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(r.status===204)return null;const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||Object.values(d.validationErrors||{})[0]||'Request failed');return d}
function toast(msg,bad=false){const t=$('toast');t.textContent=msg;t.className=bad?'bad':'show';setTimeout(()=>t.className='',2800)}
async function init(){try{me=await api('/auth/me');showApp();await loadReference();await refresh()}catch{}}
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userBadge').textContent=`${me.employeeName||me.username} · ${me.role}`;$('welcome').textContent=`Welcome, ${me.employeeName||me.username}`;$('roleSummary').textContent=me.role==='ADMIN'?'System-wide leave and people administration.':me.role==='MANAGER'?'Your leave plus approvals for your direct reports.':'Your personal leave page and leave balance.';
document.querySelectorAll('.managerOnly').forEach(x=>x.classList.toggle('hidden',!['ADMIN','MANAGER'].includes(me.role)));document.querySelectorAll('.adminOnly').forEach(x=>x.classList.toggle('hidden',me.role!=='ADMIN'));document.querySelectorAll('.managerOnlyPage').forEach(x=>x.classList.toggle('hidden',!['ADMIN','MANAGER'].includes(me.role)));document.querySelectorAll('.adminOnlyPage').forEach(x=>x.classList.toggle('hidden',me.role!=='ADMIN'));
if(me.role==='EMPLOYEE'){document.querySelector('[data-page="dashboard"]').classList.add('hidden');document.querySelector('[data-page="leaves"]').classList.add('active');document.querySelector('[data-page="leaves"]').click()}else document.querySelector('[data-page="dashboard"]').click();}
async function loadReference(){const [types,deps]=await Promise.all([api('/reference/leave-types'),api('/reference/departments')]);$('leaveType').innerHTML=types.map(t=>`<option value="${t.id}">${esc(t.name)} · ${t.annualLimit} days</option>`).join('');$('empDepartment').innerHTML=deps.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('');if(me.role==='ADMIN'){const ms=await api('/employees/managers');$('empManager').innerHTML='<option value="">No manager</option>'+ms.map(m=>`<option value="${m.id}">${esc(m.name)} · ${esc(m.username)}</option>`).join('');}else $('managerField').classList.add('hidden');if(me.role!=='ADMIN'){$('empRole').value='EMPLOYEE';$('roleField').classList.add('hidden');}}
async function refresh(){await loadDashboard();await loadMine();if(['ADMIN','MANAGER'].includes(me.role)){await loadApprovals();await loadTeam()}if(me.role==='ADMIN')await loadAudit()}
async function loadDashboard(){const d=await api('/dashboard');$('stats').innerHTML=[['My balance',d.myBalance],['My pending',d.myPending],['My approved',d.myApproved],['Team pending',d.teamPending]].map(x=>`<div class="stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('dashboardMine').innerHTML=leaveRows((await api('/leaves/mine')).slice(0,5),false)}
function leaveRows(items,management=false){if(!items.length)return '<div class="empty">No leave requests found.</div>';return `<div class="table-wrap"><table><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Days</th><th>Status</th>${management?'<th>Action</th>':''}</tr></thead><tbody>${items.map(l=>`<tr><td><b>${esc(l.employeeName)}</b><small>${esc(l.department)}</small></td><td>${esc(l.leaveType)}</td><td>${l.startDate} → ${l.endDate}</td><td>${l.days}</td><td><span class="pill ${l.status}">${l.status}</span></td>${management?`<td>${l.status==='PENDING'?`<div class="actions"><button onclick="decide(${l.id},true)">Approve</button><button class="danger" onclick="decide(${l.id},false)">Reject</button></div>`:'<span class="muted">Completed</span>'}</td>`:''}</tr>`).join('')}</tbody></table></div>`}
async function loadMine(){if(!$('mineLeaves'))return;$('mineLeaves').innerHTML=leaveRows(await api('/leaves/mine'),false)}
async function loadApprovals(){if(!['ADMIN','MANAGER'].includes(me.role))return;const status=$('statusFilter').value;const d=await api(`/leaves?page=0&size=50${status?'&status='+status:''}`);$('allLeaves').innerHTML=leaveRows(d.content,true)}
async function loadTeam(){if(!['ADMIN','MANAGER'].includes(me.role))return;const d=await api('/employees?page=0&size=50');$('employees').innerHTML=d.content.length?`<div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Department</th><th>Balance</th><th>Role</th><th>Manager</th><th>Active</th></tr></thead><tbody>${d.content.map(e=>`<tr><td><b>${esc(e.name)}</b><small>${esc(e.username)}</small></td><td>${esc(e.email)}</td><td>${esc(e.department)}</td><td>${e.leaveBalance}</td><td>${e.role}</td><td>${esc(e.managerName||'—')}</td><td>${e.active?'Active':'Inactive'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No direct reports.</div>'}
async function loadAudit(){const d=await api('/audit?page=0&size=50');$('audit').innerHTML=d.content.length?`<div class="table-wrap"><table><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Entity</th><th>Description</th></tr></thead><tbody>${d.content.map(x=>`<tr><td>${x.timestamp?.replace('T',' ')||''}</td><td>${esc(x.username)}</td><td>${esc(x.action)}</td><td>${esc(x.entityType)} #${x.entityId}</td><td>${esc(x.description)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No audit records.</div>'}
async function decide(id,approve){const comment=prompt(approve?'Approval comment (optional)':'Rejection reason (optional)','');if(comment===null)return;try{await api(`/leaves/${id}/${approve?'approve':'reject'}`,{method:'PUT',body:JSON.stringify({comment})});toast(approve?'Leave approved':'Leave rejected');await refresh()}catch(e){toast(e.message,true)}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{me=await api('/auth/login',{method:'POST',body:JSON.stringify({username:$('username').value,password:$('password').value})});showApp();await loadReference();await refresh()}catch(x){$('loginError').textContent=x.message}});
$('leaveForm').addEventListener('submit',async e=>{e.preventDefault();try{await api(`/leaves/employee/${me.employeeId}`,{method:'POST',body:JSON.stringify({leaveTypeId:Number($('leaveType').value),startDate:$('startDate').value,endDate:$('endDate').value,reason:$('reason').value})});$('leaveForm').reset();$('leaveMessage').textContent='Leave request submitted to your direct manager.';toast('Leave request submitted');await refresh()}catch(x){$('leaveMessage').textContent=x.message}});
$('employeeForm').addEventListener('submit',async e=>{e.preventDefault();try{const role=$('empRole').value;await api('/employees',{method:'POST',body:JSON.stringify({name:$('empName').value,email:$('empEmail').value,username:$('empUsername').value,password:$('empPassword').value,departmentId:Number($('empDepartment').value),joiningDate:$('empJoining').value,role,managerId:$('empManager').value?Number($('empManager').value):null})});$('employeeForm').reset();$('employeeMessage').textContent=me.role==='MANAGER'?'Employee added to your team.':'Employee account created.';toast('Employee created');await loadTeam()}catch(x){$('employeeMessage').textContent=x.message}});
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$('page-'+n.dataset.page).classList.remove('hidden')});
$('statusFilter').onchange=loadApprovals;$('logoutBtn').onclick=async()=>{await api('/auth/logout',{method:'POST'});location.reload()};init();
